[package]
name = "beets2mpd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.29.0", features = ["bundled"] }

[package.metadata.cross.target.aarch64-unknown-linux-gnu]

